on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.0"

      - name: Build
        run: scripts/buildprod.sh

      - id: gcloud auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Debug gcloud
        run: gcloud info

      - name: Push to Google Artifact Registry
        run: gcloud builds submit --tag europe-west8-docker.pkg.dev/notely-456921/notely-ar-repo/notely:latest .
